/*************************************************************************
 * Fichero : CALCU.H                                                     *
 * Fichero que contiene las funciones necesarias para el uso de una      *
 * calculadora.                                                          *
 *************************************************************************
 * Fecha creaci¢n : 27/5/1997                                            *
 * Fecha £ltima modificaci¢n : 27/5/97                                   *
 * (c)1997 Luis Fernando Santocildes Romero                              *
 *************************************************************************
 * V1.0 : 27/5/97                                                        *
 *        - Primera versi¢n                                              *
 *************************************************************************/

/******************************** Prototipos ********************************/
extern void calculadora (void);
                                        // Muestra una calculadora en pantalla

